name: CLI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: CMake BingoCLI
      run: cd BingoCLI && cmake .
    - name: g++ BingoCLI
      run: cd BingoCLI && make -j
      
