name: CLIWindows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: CMake BingoCLI
        run: cd BingoCLI  ; if ($?) { cmake . }
      - name: g++ BingoCLI
        run: cd BingoCLI  ; if ($?) { make -j }
      
