name: Core

on: [push]

jobs:
  build:

    runs-on: ubuntu
    
    steps:
    - uses: actions/checkout@v1
    - name: CMake BingoCore
      run: cd BingoCore && cmake .
    - name: g++ BingoCore
      run: cd BingoCore && make -j
      
