name: CoreTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: CMake BingoCore
      run: cd BingoTest && cmake .
    - name: g++ BingoCore
      run: cd BingoTest && make
      
