name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: CMake BingoCore
      run: cd BingoCore && cmake .
    - name: g++ BingoCore
      run: cd BingoCore && make
    - name: CMake BingoCLI
      run: cd BingoCLI && cmake .
    - name: g++ BingoCLI
      run: cd BingoCLI && make
    - name: CMake BingoUI
      run: cd BingoUI && cmake .
    - name: g++ BingoUI
      run: cd BingoUI && make