name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: CMake BingoCore
      run: cd BingoCore && cmake .
    - name: G++ BingoCore
      run: cd BingoCore && make
