name: TestWindows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: CMake BingoCLI
        run: cd BingoTest ; if ($?) { cmake .}
      - name: g++ BingoTest
        run: cd BingoTest  ; if ($?) {make -j}
      - name: Run test
        run: cd BingoTest  ; if ($?) { ./BingoTest }
      
