name: TestMacOS

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: CMake BingoCLI
        run: cd BingoTest && cmake .
      - name: g++ BingoTest
        run: cd BingoTest && make -j
      - name: Run test
        run: cd BingoTest && ./BingoTest
      
