name: TestWindows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: CMake BingoCLI
        run: cd BingoTest -and cmake .
      - name: g++ BingoTest
        run: cd BingoTest -and make -j
      - name: Run test
        run: cd BingoTest -and ./BingoTest
      
