name: UI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: make build
      run: mkdir build
    - name: CMake BingoUI
      run: cd BingoUI && cmake .
    - name: g++ BingoUI
      run: cd BingoUI && make
      
