name: UIWindows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - name: make BingoUI/build
        run: mkdir BingoUI/build
      - name: CMake BingoUI
        run: cd BingoUI/build  ; if ($?) {cmake ..}
      - name: g++ BingoUI
        run: cd BingoUI/build  ; if ($?) {make -j}
      
